services:
  mongo:
    image: mongo
    restart: always
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${DB_USERNAME:-user}
      - MONGO_INITDB_ROOT_PASSWORD=${DB_PASSWORD:-password}
      - MONGO_INITDB_DATABASE=${DB_NAME:-advs_database}

  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
    environment:
      - ME_CONFIG_MONGODB_SERVER=mongo
      - ME_CONFIG_MONGODB_ADMINUSERNAME=${DB_USERNAME:-admin}
      - ME_CONFIG_MONGODB_ADMINPASSWORD=${DB_PASSWORD:-password}
  server:
    build: ./
    environment:
      - SERVER_PORT=${SERVER_PORT:-3000}
      - DB_USERNAME=${DB_USERNAME:-user}
      - DB_PASSWORD=${DB_PASSWORD:-password}
      - DB_NAME=${DB_NAME:-advs_database}
      - DB_HOST=mongodb://mongo:27017
      - COOKIE_SECRET=${COOKIE_SECRET:-paranoid}
    # environment:
    #   - PORT=3000
    #   - MONGODB_URL=mongodb://root:example@mongo:27017/
    ports:
      - 80:3000
    working_dir: /app
    # volumes:
    #   - ./:/app1
    command: npm run dev